### ISSUE TITLE
How can i create a mrc file from the response. 

### ISSUE THREAD

**Issue by sodiqdare** [NatLibFi/marc-record-js#38]
I have been trying to create a marc record file from the marc toString response, but the marc viewer i have doesnt make recognise it as  valid. 

Is this the right way to save the file?

`fs.writeFileSync('test2.mrc', fakeComponentRecord.toString())`

<img width="728" alt="image" src="https://github.com/NatLibFi/marc-record-js/assets/108657660/d2f5b093-ce6b-4284-909e-937ed95e08ad">

**Comment by ammsalme** [comment]
marc-record-js's toString() function writes a string representation of the record, but this string is not a valid MARC 21 record, that could be used in other applications.

Use https://github.com/NatLibFi/marc-record-serializers to create a record that for example MarcEdit can read.

Can you get the following working:

```
import {ISO2709} from '@natlibfi/marc-record-serializers';

fs.writeFileSync('test2.mrc', ISO2709.to(fakeComponentRecord));
```

marc-record-serializers can convert marc-record-js object from and to:

- ISO2709 = binary MARC 21 = MARC21 exchange format (see https://www.loc.gov/marc/specifications/specrecstruc.html), this is the old fashioned MARC 21 record format, that for example MarcEdit handles
- MARCXML, current XML serialization of MARC 21
- OAI-MARCXML, older XML serializations of MARC21
- Aleph Sequential, format Ex Libris Aleph's uses
- json, JSON serialization used by marc-record-js
- text, text serialization used by marc-record-js (this is what marc-record-js:s native toString() prints, too)

**Comment by sodiqdare** [comment]
Thank you, that worked!
