### ISSUE TITLE
storing json

### ISSUE THREAD

**Issue by nu-develop** [NatLibFi/marc-record-js#7]
Hi. I wonder if you have any experience with storing marc records in json?
I'm looking for a solution that allows querying specific fields and subfields, e.g. all records that contain some string in tag '245'.
I was considering MongoDB. What do you think?

**Comment by natlibfi-arlehiko** [comment]
Yeah, that's what MongoDB is built for (Querying JSON-documents).

**Comment by nu-develop** [comment]
Ok. Thanks.
